#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "pathname"
require "yaml"

module BuildPattern
  OPTIONS = proc do |opts|
    opts.banner = <<~USAGE
      Usage: build-pattern TOPICFILE [OPTIONS]
    USAGE

    opts.on "--help", -"h", "Prints this help" do
      puts opts
      exit
    end
  end

  class App
    attr_reader :topic_file

    def initialize(topic_file, validate: false)
      @topic_file = Pathname(topic_file)
      @validate = validate
    end

    def run
      errors = topics.flat_map(&:errors)
      if errors.any?
        warn errors
        exit(1)
      end

      puts ['\b(', sorted_patterns.join("|"), ')\b'].join
    end

    def sorted_patterns
      topics.flat_map(&:patterns).sort_by { |value| [-value.length, value] }
    end

    def topics
      @topics ||= begin
        topics_hash = YAML.load_file(topic_file, aliases: true)
        Topic.from_hash(topics_hash.reject { |k, _| k.start_with?(".") })
      end
    end

    def validate?
      @validate
    end

    def self.run(...)
      new(...).run
    end
  end

  class Topic
    attr_reader :name, :patterns

    def initialize(name, patterns:)
      @name = name
      @patterns = patterns
    end

    def self.from_hash(topics)
      topics.map do |name, patterns|
        patterns = patterns.map { |pattern| Array(pattern).join }
        new(name, patterns:)
      end
    end

    def errors
      patterns.map do |pattern|
        Regexp.new(pattern)
        nil
      rescue RegexpError => e
        "#{e.class}: #{e} for #{name.inspect}"
      end.compact
    end
  end
end

if $PROGRAM_NAME == __FILE__
  arguments = ARGV.dup
  options = {}
  OptionParser.new(&BuildPattern::OPTIONS).parse!(arguments, into: options)
  options.transform_keys! { |key| key.to_s.tr("-", "_").to_sym }
  BuildPattern::App.run(*arguments, **options)
end
