name: Generate regular expressions
run-name: Generating the regular expressions

on:
  workflow_run:
    workflows: [Run tests]
    types:     [completed]

jobs:
  generate-regex:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  "3.3"
          bundler-cache: true
      - name: Install dependencies
        run:  bundle install
      - name: Generate regular expression
        run: ./build-pattern topics.yml categories.yml --except Publishers > regexes/all-things-ttrpg.txt
      - name: Generate non-WotC/Pathfinder expression
        run: ./build-pattern topics.yml categories.yml --only "Wizards of the Coast, Dungeons & Dragons, Pathfinder" > regexes/wotc-pathfinder.txt
      - name: Archive regular expressions
        uses: actions/upload-artifact@v4
        with:
          name: regexes
          path: regexes
