name: Generate regular expression
run-name: Generating the regular expression

on:
  workflow_run:
    workflows: [Run tests]
    types:     [completed]

jobs:
  generate-regex:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        run:  bundle install
      - name: Generate regular expression
        run: ./build-pattern topics.yml
