name: Run RuboCop
run-name: Running RuboCop

on:
  push:
    branches: [main]

jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  "3.3"
          bundler-cache: true
      - name: Install dependencies
        run:  bundle install
      - name: Run RuboCop
        run:  bundle exec rubocop
